// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgbU9MmbVuvjcmEzZ0GKx9i16m3e-UOUA',
    appId: '1:142189059677:web:3f462d2d2d3445829577b4',
    messagingSenderId: '142189059677',
    projectId: 'tiktok-78fc6',
    authDomain: 'tiktok-78fc6.firebaseapp.com',
    databaseURL: 'https://tiktok-78fc6-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-78fc6.appspot.com',
    measurementId: 'G-GJ0B1GJ9D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFX8IoUwpYK7s7CGCZ4F3Hi8pIgpFGGX4',
    appId: '1:142189059677:android:e5ea8e9228b21f2f9577b4',
    messagingSenderId: '142189059677',
    projectId: 'tiktok-78fc6',
    databaseURL: 'https://tiktok-78fc6-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-78fc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNr1iXyOMKasxkTgTjvmehKRsyKGBBp4E',
    appId: '1:142189059677:ios:ace0f360e29397869577b4',
    messagingSenderId: '142189059677',
    projectId: 'tiktok-78fc6',
    databaseURL: 'https://tiktok-78fc6-default-rtdb.firebaseio.com',
    storageBucket: 'tiktok-78fc6.appspot.com',
    iosBundleId: 'com.codingliquids.flutterArchitectures',
  );
}
